from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable

import yaml

from src.config_loader import load_rules
from src.excel_io import atomic_output_path

from .accounting_models import CASH_FLOWS, ManagedAccountingRule


class AccountingYamlPublisher:
    def __init__(self, path: str | Path):
        self.path = Path(path)

    def load_mapping(self) -> dict[str, Any]:
        with self.path.open("r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle) or {}
        if not isinstance(data, dict) or not isinstance(data.get("rules", []), list):
            raise ValueError(f"YAML Nghiệp vụ kế toán không hợp lệ: {self.path}")
        return data

    def publish(self, managed_records: Iterable[ManagedAccountingRule]) -> Path:
        data = self.load_mapping()
        records = list(managed_records)
        user_records = [record for record in records if record.source == "user"]
        overrides = [record for record in records if record.source == "override"]
        managed_ids = {record.rule_id for record in user_records}
        builtin_rules = [
            item
            for item in data.get("rules", []) or []
            if not (isinstance(item, dict) and str(item.get("rule_id", "") or "") in managed_ids)
        ]
        active = [record for record in user_records if record.active and not record.deleted]
        active.sort(
            key=lambda item: (
                item.flow,
                -max((len(alias) for alias in item.active_aliases), default=0),
                item.created_at,
                item.record_id,
            )
        )
        data["rules"] = builtin_rules + [self._to_yaml(record) for record in active]
        override_ids = {record.rule_id for record in overrides}
        disabled = [
            str(rule_id).strip()
            for rule_id in data.get("disabled_rule_ids", []) or []
            if str(rule_id or "").strip() and str(rule_id).strip() not in override_ids
        ]
        disabled.extend(record.rule_id for record in overrides if not record.active or record.deleted)
        disabled = list(dict.fromkeys(disabled))
        if disabled:
            data["disabled_rule_ids"] = disabled
        else:
            data.pop("disabled_rule_ids", None)

        with atomic_output_path(self.path) as temporary_path:
            with temporary_path.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write("# Generated by Quản lý dữ liệu sao kê.\n")
                yaml.safe_dump(data, handle, allow_unicode=True, sort_keys=False, width=120)
            with temporary_path.open("r", encoding="utf-8") as handle:
                validated = yaml.safe_load(handle) or {}
            if not isinstance(validated, dict) or not isinstance(validated.get("rules", []), list):
                raise ValueError("Không xác thực được YAML Nghiệp vụ kế toán vừa sinh")

        # Exercise the exact loader used by bank_agent.py.
        load_rules(None, self.path)
        return self.path

    @staticmethod
    def _to_yaml(record: ManagedAccountingRule) -> dict[str, Any]:
        account = "1111" if record.flow in CASH_FLOWS else record.account.strip()
        requires_object, object_catalog = _object_policy(account)
        return {
            "flow": record.flow,
            "rule_id": record.rule_id,
            "direction": "money_out" if record.flow in {"bao_no", "thu_tien_mat"} else "money_in",
            "use_case": record.use_case.strip(),
            "account": account,
            "bank_scope": ["VCB", "ACB", "MSB"],
            "include_keywords": list(record.active_aliases),
            "context_keywords": [],
            "exclude_keywords": [],
            "auto_process": True,
            "priority": 5,
            "requires_object": requires_object,
            "object_catalog": object_catalog,
        }


def _object_policy(account: str) -> tuple[bool, str]:
    value = str(account or "").strip()
    if value == "331":
        return True, "payable"
    if value == "131":
        return True, "receivable"
    if value == "141":
        return True, "internal"
    return False, "none"
