from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable

import yaml

from src.excel_io import atomic_output_path
from src.reason_aliases import load_reason_purposes

from .payment_models import ManagedPaymentPurpose


class PaymentYamlPublisher:
    def __init__(self, path: str | Path):
        self.path = Path(path)

    def load_mapping(self) -> dict[str, Any]:
        if not self.path.exists():
            return {}
        with self.path.open("r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle) or {}
        if not isinstance(data, dict):
            raise ValueError(f"YAML Loại thanh toán không hợp lệ: {self.path}")
        return data

    def config_records(self) -> list[ManagedPaymentPurpose]:
        records: list[ManagedPaymentPurpose] = []
        for item in self.load_mapping().get("purposes", []) or []:
            if not isinstance(item, dict):
                continue
            records.append(
                ManagedPaymentPurpose.from_config(
                    str(item.get("code", "") or ""),
                    str(item.get("label", "") or ""),
                    [str(alias) for alias in item.get("aliases", []) or []],
                )
            )
        return records

    def publish(self, managed_records: Iterable[ManagedPaymentPurpose]) -> Path:
        data = self.load_mapping()
        managed = list(managed_records)
        by_code = {record.code: record for record in managed}
        emitted: set[str] = set()
        purposes: list[dict[str, Any]] = []

        for item in data.get("purposes", []) or []:
            if not isinstance(item, dict):
                continue
            code = str(item.get("code", "") or "").strip()
            record = by_code.get(code)
            if record is None:
                purposes.append(item)
                continue
            emitted.add(code)
            if record.active and not record.deleted:
                purposes.append(self._to_yaml(record))

        for record in managed:
            if record.code in emitted or not record.active or record.deleted:
                continue
            purposes.append(self._to_yaml(record))

        data["purposes"] = purposes
        with atomic_output_path(self.path) as temporary_path:
            with temporary_path.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write("# Generated by Quản lý dữ liệu sao kê.\n")
                yaml.safe_dump(data, handle, allow_unicode=True, sort_keys=False, width=120)
            with temporary_path.open("r", encoding="utf-8") as handle:
                validated = yaml.safe_load(handle) or {}
            if not isinstance(validated, dict) or not isinstance(validated.get("purposes", []), list):
                raise ValueError("Không xác thực được YAML Loại thanh toán vừa sinh")

        # Exercise the exact tolerant loader used by the processor as a final compatibility check.
        load_reason_purposes(self.path)
        return self.path

    @staticmethod
    def _to_yaml(record: ManagedPaymentPurpose) -> dict[str, Any]:
        return {
            "code": record.code,
            "label": record.label,
            "aliases": list(record.active_aliases),
        }
