from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable

import yaml

from src.excel_io import atomic_output_path
from src.normalizer import normalize_text

from .models import CATALOG_KEYS, MATCH_ALIAS, MATCH_EXACT_PHRASE, ManagedAlias
from .paths import RuleManagerPaths


class ObjectYamlPublisher:
    def __init__(self, paths: RuleManagerPaths):
        self.paths = paths

    def publish(self, managed_aliases: Iterable[ManagedAlias]) -> tuple[Path, Path]:
        aliases_data = self._load_mapping(self.paths.object_aliases_path)
        overrides_data = self._load_mapping(self.paths.object_overrides_path)
        records = list(managed_aliases)

        # Remove every user-managed alias from both destinations first. This
        # makes changing match type and disabling a rule deterministic while
        # preserving configuration entries that are not managed by the GUI.
        for record in records:
            self._remove_flexible_alias(aliases_data, record.catalog, record.alias)
            self._remove_exact_phrase(overrides_data, record.catalog, record.alias)

        for record in records:
            if not record.active:
                continue
            if record.match_type == MATCH_EXACT_PHRASE:
                section = self._catalog_override(overrides_data, record.catalog)
                exact_phrases = section.setdefault("exact_phrases", {})
                exact_phrases[record.alias.strip()] = record.object_code.strip()
            elif record.match_type == MATCH_ALIAS:
                section = self._alias_catalog(aliases_data, record.catalog)
                values = section.setdefault(record.object_code.strip(), [])
                if isinstance(values, str):
                    values = [values]
                normalized_existing = {normalize_text(value) for value in values}
                if normalize_text(record.alias) not in normalized_existing:
                    values.append(record.alias.strip())
                section[record.object_code.strip()] = values
            else:
                raise ValueError(f"Kiểu alias không hỗ trợ: {record.match_type}")

        self._write_yaml(
            self.paths.object_aliases_path,
            aliases_data,
            header=(
                "# Generated by Bank Agent Rule Manager.\n"
                "# User changes are stored in data/rule_manager/object_rules.user.json.\n"
            ),
        )
        self._write_yaml(
            self.paths.object_overrides_path,
            overrides_data,
            header=(
                "# Generated by Bank Agent Rule Manager.\n"
                "# Do not edit while Rule Manager is publishing.\n"
            ),
        )
        return self.paths.object_aliases_path, self.paths.object_overrides_path

    def alias_targets(self) -> dict[str, dict[str, list[dict[str, str]]]]:
        """Return normalized alias -> target records by catalog."""
        result = {catalog: {} for catalog in CATALOG_KEYS}
        aliases_data = self._load_mapping(self.paths.object_aliases_path)
        overrides_data = self._load_mapping(self.paths.object_overrides_path)
        for catalog in CATALOG_KEYS:
            section = aliases_data.get(catalog, {}) or {}
            if isinstance(section, dict):
                for code, values in section.items():
                    values = [values] if isinstance(values, str) else list(values or [])
                    for alias in values:
                        self._add_target(result, catalog, alias, str(code), MATCH_ALIAS)
            override = overrides_data.get(catalog, {}) or {}
            exact_phrases = override.get("exact_phrases", {}) if isinstance(override, dict) else {}
            if isinstance(exact_phrases, dict):
                for phrase, code in exact_phrases.items():
                    self._add_target(result, catalog, phrase, str(code), MATCH_EXACT_PHRASE)
        return result

    def aliases_for_object(self, catalog: str, object_code: str) -> list[dict[str, str]]:
        code_norm = normalize_text(object_code)
        rows: list[dict[str, str]] = []
        for alias_norm, targets in self.alias_targets().get(catalog, {}).items():
            for target in targets:
                if normalize_text(target["object_code"]) != code_norm:
                    continue
                rows.append(
                    {
                        "alias": target["alias"],
                        "alias_norm": alias_norm,
                        "match_type": target["match_type"],
                    }
                )
        return sorted(rows, key=lambda row: (row["match_type"], row["alias_norm"]))

    @staticmethod
    def _add_target(
        result: dict[str, dict[str, list[dict[str, str]]]],
        catalog: str,
        alias: Any,
        object_code: str,
        match_type: str,
    ) -> None:
        alias_text = str(alias or "").strip()
        alias_norm = normalize_text(alias_text)
        if not alias_norm:
            return
        result[catalog].setdefault(alias_norm, []).append(
            {"alias": alias_text, "object_code": object_code, "match_type": match_type}
        )

    @staticmethod
    def _load_mapping(path: Path) -> dict[str, Any]:
        if not path.exists():
            return {}
        with path.open("r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle) or {}
        if not isinstance(data, dict):
            raise ValueError(f"YAML phải có cấu trúc mapping: {path}")
        return data

    @staticmethod
    def _alias_catalog(data: dict[str, Any], catalog: str) -> dict[str, Any]:
        section = data.setdefault(catalog, {})
        if not isinstance(section, dict):
            raise ValueError(f"Cấu trúc alias của {catalog} không hợp lệ")
        return section

    @staticmethod
    def _catalog_override(data: dict[str, Any], catalog: str) -> dict[str, Any]:
        section = data.setdefault(catalog, {})
        if not isinstance(section, dict):
            raise ValueError(f"Cấu trúc override của {catalog} không hợp lệ")
        return section

    def _remove_flexible_alias(self, data: dict[str, Any], catalog: str, alias: str) -> None:
        alias_norm = normalize_text(alias)
        section = self._alias_catalog(data, catalog)
        for code, values in list(section.items()):
            if isinstance(values, dict):
                continue
            original = [values] if isinstance(values, str) else list(values or [])
            filtered = [value for value in original if normalize_text(value) != alias_norm]
            if filtered:
                section[code] = filtered
            elif original:
                section.pop(code, None)

    def _remove_exact_phrase(self, data: dict[str, Any], catalog: str, alias: str) -> None:
        alias_norm = normalize_text(alias)
        section = self._catalog_override(data, catalog)
        exact_phrases = section.setdefault("exact_phrases", {})
        if not isinstance(exact_phrases, dict):
            raise ValueError(f"exact_phrases của {catalog} không hợp lệ")
        for phrase in list(exact_phrases):
            if normalize_text(phrase) == alias_norm:
                exact_phrases.pop(phrase, None)

    @staticmethod
    def _write_yaml(path: Path, data: dict[str, Any], header: str = "") -> None:
        with atomic_output_path(path) as temporary_path:
            with temporary_path.open("w", encoding="utf-8", newline="\n") as handle:
                if header:
                    handle.write(header)
                yaml.safe_dump(data, handle, allow_unicode=True, sort_keys=False, width=120)
            with temporary_path.open("r", encoding="utf-8") as handle:
                validated = yaml.safe_load(handle) or {}
            if not isinstance(validated, dict):
                raise ValueError(f"Không xác thực được YAML vừa sinh: {path}")
